import DS from 'ember-data';

const {Model, attr, hasMany} = DS;

export default Model.extend({
	title: attr('string'),
	content: attr('string'),
	excerpt: attr('string'),
	slug: attr('string'),
	date: attr('date'),
	featured_media: attr('number'),
	format: attr(),
	tags: hasMany('tag', {async: true}),

	application_brewery: attr(),
	application_cows: attr(),
	application_meat: attr(),
	application_milk: attr(),
	application_laundry: attr(),
	application_poultry: attr(),
	application_pigs: attr(),
	advantages_en: attr('string'),
	advantages_ru: attr('string'),
	breathe_en: attr('string'),
	breathe_ru: attr('string'),
	color_code: attr('string'),
	color_code_style: attr('string'),
	color_name_ru: attr('string'),
	color_name_en: attr('string'),
	consistency: attr('string'),
	density: attr('number'),
	description_en: attr('string'),
	description_ru: attr('string'),
	environment_en: attr('string'),
	environment_ru: attr('string'),
	eyes_en: attr('string'),
	eyes_ru: attr('string'),
	foaming: attr('boolean'),
	hands_en: attr('string'),
	hands_ru: attr('string'),
	icons: attr(),
	image: attr('string'),
	industry: attr(),
	leaflet: attr(),
	mark: attr(),
	package_barrel: attr('number'),
	package_bucket: attr('number'),
	package_can: attr('number'),
	package_cube: attr('number'),
	package_sack: attr('number'),
	pds: attr(),
	ph: attr('number'),
	registration: attr(),
	registration_date: attr('string'),
	registration_number: attr('string'),
	risk_phrases: attr('string'),
	safety: attr(),
	safety_phrases: attr('string'),
	sds: attr(),
	storage_en: attr('string'),
	storage_ru: attr('string'),
	product_type: attr(),
	temp_from: attr('number'),
	temp_to: attr('number'),
	thumbnail: attr('string'),
	usage_en: attr('string'),
	usage_ru: attr('string')
});
